<?php

namespace MDB\RedacteurBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RedacteurRepository extends EntityRepository {

  public function getAll() {
    
  }

  public function create($redacteur) {
    $this->getEntityManager()->persist($redacteur);
    $this->getEntityManager()->flush();
  }

  public function delete($redacteur) {
    $this->getEntityManager()->remove($redacteur);
    $this->getEntityManager()->flush();
  }
  public function update($redacteur) {
    $this->getEntityManager()->merge($redacteur);
    $this->getEntityManager()->flush();
  }

}
