security:
    providers:
        fos_userbundle:
          id: fos_user.user_provider.username
#(dis)allows access to urls 
    firewalls:
        main:
          pattern: ^/
          form_login:
            provider: fos_userbundle
            csrf_provider: form.csrf_provider
          logout: 
            path: /logout
            target: /
          anonymous: true
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
#handles all other urls
        default:
            anonymous: ~
            http_basic: ~
    
    access_control:
      #require ROLE_ADMIN for /securitytest*
      - {path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY}
      - {path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY}
      - {path: ^/resetting, roles: IS_AUTHENTICATED_ANONYMOUSLY}
      - { path: ^/admin/users, roles: ROLE_SUPER_ADMIN }
      - { path: ^/admin, roles: ROLE_ADMIN }
#encoders    
    encoders: 
      FOS\UserBundle\Model\UserInterface: sha512
      
    role_hierarchy:
      ROLE_ADMIN:       ROLE_USER
      ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]