<?php

namespace MDB\ModellenBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * KleurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HaarKleurRepository extends EntityRepository
{
}
