<?php

namespace MDB\ModellenBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PostcodeNummerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaatsnaamRepository extends EntityRepository
{
}
