<?php

namespace MDB\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository {

  /**
   * haalt alle users op
   * @return object $user:User object
   */
  function getAll() {
    $qb = $this->getEntityManager()->createQueryBuilder();
    $users = $qb->select('u')->from('MDBUserBundle:User', 'u')->getQuery()->getResult();
    return $users;
  }

  /**
   * haalt user op op basis van de nicknaam 
   * @param string $nicknaam
   * @return object $user: User object
   */
  function getByNickNaam($nicknaam) {
    $em = $this->getEntityManager();
    $qb = $em->createQueryBuilder();
    $user = $qb->select('u')->from('MDBUserBundle:User', 'u')->where($qb->expr()->eq('u.nicknaam', '?1'))->setParameter(1, $nicknaam)->getQuery()->getOneOrNullResult();
    return $user;
  }

  /**
   * maakt user aan
   * @param object $user
   */
  function createUser($user) {
    $this->getEntityManager()->persist($user);
    $this->getEntityManager()->flush();
  }

  /**
   * werkt gegevens van een user bij
   * @param object $user
   */
  function updateUser($user) {
    $this->getEntityManager()->flush();
  }

  /**
   * verwijdert user
   */
  function removeUser($user) {
    $this->getEntityManager()->remove($user);
    $this->getEntityManager()->flush();
  }

}
